### ISSUE TITLE
FCustomVector

### ISSUE THREAD

**Issue by leyleyzhou** [hxhb/ue4-recast-detour#1]
大佬  编译不过 没有UE4RecastHelper::FCustomVector这个结构体哈

**Comment by leyleyzhou** [comment]
> 大佬 编译不过 没有UE4RecastHelper::FCustomVector这个结构体哈
我换成
FVector3可以了

**Comment by hxhb** [comment]
> > 大佬 编译不过 没有UE4RecastHelper::FCustomVector这个结构体哈
> 我换成
> FVector3可以了 

嗯，之前给这个类改名字了，漏掉了没替换。

**Comment by hxhb** [comment]
fixed in [8dd0d5b](https://github.com/hxhb/ue4-recast-detour/commit/8dd0d5b047414638a621132a47d2b60589d41099)
