### ISSUE TITLE
Support for UE5?

### ISSUE THREAD

**Issue by PacaPop** [hxhb/ue4-recast-detour#4]
Hello! Is this compatible with UE5??

**Comment by hxhb** [comment]
> Hello! Is this compatible with UE5??

I haven't tested it in UE5 and I am not sure if it can be perfectly compatible with UE5.

**Comment by PacaPop** [comment]
Are you planning to make it compatible with ue5? Thankss

**Comment by hxhb** [comment]
@PacaPop Yes, after the official version of ue5 is released, I plan to test and develop on ue5.
