### ISSUE TITLE
用插件导出的.bin是否和RecastDemo导出的.bin不同

### ISSUE THREAD

**Issue by WenzhiShao** [hxhb/ue4-recast-detour#9]
你好，有个问题想请教一下您。我发现通过您发布的unreal插件导出的bin文件和用RecastDemo.exe导出的.bin似乎是不一样的（选择Solo Mesh-> 选择导出的M mesh->build->save得到的bin）。通过RecastDemo导出的bin文件，用您的ue4-recast-detour工具包，无法DeSerializedtNavMesh。或者插件导出的.bin，ReactDemo也不能Load
请问您导出的bin和demo导出的bin有什么具体的区别呢。

**Comment by hxhb** [comment]
详见https://imzlp.com/posts/20203/
